### PR TITLE
Setting releaseDate when versionReleased is true

### PR DESCRIPTION
**Pull request by varnerknut**
How about setting the _releaseDate_ when versionReleased is true. 
Update Version supports this through the _releaseDate_ parameter

### CODE REVIEW

**Comment by tom-mrnk-github** [comment]
We would be happy as well to have this merged. Thanks.

**Comment by tom-mrnk-github** [comment]
Anyone? Thanks

**Comment by luxemate** [comment]
I was about to create the same PR, but here it is. :)

@werthdavid @benjaminalbanese Merge, please.

**Review by bachlmn — APPROVED** [review]

**Comment by benjaminalbanese** [comment]
Sorry for the delay, seems we somehow we didn't get a notification for this. 
We'll have a look right now.

**Comment by benjaminalbanese** [comment]
availble as version 1.4.0 now - happy development everyone!

**Comment by luxemate** [comment]
@benjaminalbanese Thank you!

**Pull request merged**
